
/****** Object:  Table [dbo].[ITEM_PEDIDO]    Script Date: 14/01/2021 16:02:14 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ITEM_PEDIDO](
	[ID_ITEM_PEDIDO] [int] IDENTITY(1,1) NOT NULL,
	[ID_PEDIDO] [int] NOT NULL,
	[ID_PRODUTO] [int] NOT NULL,
	[QTD_ITEM_PEDIDO] [int] NULL,
	[VLR_ITEM_PEDIDO_UNITARIO] [decimal](12, 2) NULL,
	[VLR_ITEM_PEDIDO_TOTAL] [decimal](18, 2) NULL,
 CONSTRAINT [PK_ITEM_PEDIDO] PRIMARY KEY NONCLUSTERED 
(
	[ID_ITEM_PEDIDO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[ITEM_PEDIDO] ADD  DEFAULT ((0)) FOR [QTD_ITEM_PEDIDO]
GO

ALTER TABLE [dbo].[ITEM_PEDIDO] ADD  DEFAULT ((0)) FOR [VLR_ITEM_PEDIDO_UNITARIO]
GO

ALTER TABLE [dbo].[ITEM_PEDIDO] ADD  DEFAULT ((0)) FOR [VLR_ITEM_PEDIDO_TOTAL]
GO

ALTER TABLE [dbo].[ITEM_PEDIDO]  WITH CHECK ADD  CONSTRAINT [FK_ITEM_PEDIDO_PEDIDO] FOREIGN KEY([ID_PEDIDO])
REFERENCES [dbo].[PEDIDO] ([ID_PEDIDO])
GO

ALTER TABLE [dbo].[ITEM_PEDIDO] CHECK CONSTRAINT [FK_ITEM_PEDIDO_PEDIDO]
GO

ALTER TABLE [dbo].[ITEM_PEDIDO]  WITH CHECK ADD  CONSTRAINT [FK_ITEM_PEDIDO_PRODUTO] FOREIGN KEY([ID_PRODUTO])
REFERENCES [dbo].[PRODUTO] ([ID_PRODUTO])
GO

ALTER TABLE [dbo].[ITEM_PEDIDO] CHECK CONSTRAINT [FK_ITEM_PEDIDO_PRODUTO]
GO


