USE [GATEWARE]
GO

/****** Object:  Table [dbo].[PEDIDO]    Script Date: 20/01/2021 19:17:05 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PEDIDO](
	[ID_PEDIDO] [int] IDENTITY(1,1) NOT NULL,
	[ID_CLIENTE] [int] NULL,
	[VLR_PEDIDO] [decimal](18, 2) NULL,
	[DAT_PEDIDO] [datetime] NULL,
	[COD_VENDEDOR] [int] NULL,
 CONSTRAINT [PK_PEDIDO] PRIMARY KEY NONCLUSTERED 
(
	[ID_PEDIDO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[PEDIDO] ADD  DEFAULT ((0)) FOR [VLR_PEDIDO]
GO

ALTER TABLE [dbo].[PEDIDO] ADD  DEFAULT (getdate()) FOR [DAT_PEDIDO]
GO

ALTER TABLE [dbo].[PEDIDO]  WITH CHECK ADD  CONSTRAINT [FK_CLIENTE_ID_CLIENTE] FOREIGN KEY([ID_CLIENTE])
REFERENCES [dbo].[CLIENTE] ([ID_CLIENTE])
GO

ALTER TABLE [dbo].[PEDIDO] CHECK CONSTRAINT [FK_CLIENTE_ID_CLIENTE]
GO


