USE [GATEWARE]
GO

/****** Object:  Table [dbo].[PRODUTO]    Script Date: 20/01/2021 18:37:20 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
/*
Código;
• Código de barras;
• Descrição;
• Valor;
• Saldo em estoque;
• Status.
*/
CREATE TABLE [dbo].[PRODUTO](
	[ID_PRODUTO] [int] IDENTITY(1,1) NOT NULL,
	[DSC_PRODUTO] [varchar](150) NULL,
	[VLR_PRODUTO] [decimal](18, 2) NULL,
	[SLD_PRODUTO] [int] NULL,
	[STA_PRODUTO] [bit] NULL,
	[BAR_PRODUTO] VARCHAR(50) NULL,
 CONSTRAINT [PK_PRODUTO] PRIMARY KEY NONCLUSTERED 
(
	[ID_PRODUTO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[PRODUTO] ADD  DEFAULT ((0)) FOR [VLR_PRODUTO]
GO

ALTER TABLE [dbo].[PRODUTO] ADD  DEFAULT ((0)) FOR [SLD_PRODUTO]
GO


